services:
  app:
    image: mrvautin/fitns:latest
    container_name: fitns
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/var/www/config/app
      - ./build:/var/www/build
      - ./storage/database:/var/www/storage/database
      - ./storage/files:/var/www/storage/files
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "1.0.0"
