services:
  app:
    image: mrvautin/fitns:latest
    container_name: fitns
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "1.0.0"
